name: Dependancy Review
on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Dependancy Review
        uses: actions/dependancy-review-action@v3
        with:
          comment-summery-in-pr: true
